/* Generated by tools/gen_dials.py - do not edit by hand.
 * Geometry of the artwork in dials.c. Every image has its pivot in
 * its centre; angles are LVGL's, 0 = 3 o'clock, clockwise.
 */
#pragma once
#include "lvgl.h"

extern const lv_img_dsc_t dial_rpm;
extern const lv_img_dsc_t dial_clt;
extern const lv_img_dsc_t dial_iat;
extern const lv_img_dsc_t dial_boost;
extern const lv_img_dsc_t dial_afr;
extern const lv_img_dsc_t needle_big;
extern const lv_img_dsc_t needle_temp;
extern const lv_img_dsc_t needle_turbo;
extern const lv_img_dsc_t hub_big;
extern const lv_img_dsc_t hub_temp;
extern const lv_img_dsc_t hub_turbo;

#define BIG_SWEEP_START          135
#define BIG_SWEEP                270
#define BIG_SIZE                 500
#define RPM_MAX                  8000
#define RPM_REDLINE              7000

#define TEMP_SWEEP_START         220
#define TEMP_SWEEP               100
#define CLT_MIN                  40
#define CLT_MAX                  130
#define IAT_MIN                  0
#define IAT_MAX                  80

#define TURBO_SWEEP_START        180
#define TURBO_SWEEP              210
#define BOOST_MIN                (-1.00f)
#define BOOST_MAX                (2.00f)
#define AFR_MIN                  (10.00f)
#define AFR_MAX                  (18.00f)

#define NEEDLE_BIG_PIVOT_X       35
#define NEEDLE_BIG_PIVOT_Y       11
#define NEEDLE_TEMP_PIVOT_X      16
#define NEEDLE_TEMP_PIVOT_Y      7
#define NEEDLE_TURBO_PIVOT_X     15
#define NEEDLE_TURBO_PIVOT_Y     7
