/* Generated by tools/gen_themes.py - do not edit by hand. */
#pragma once
#include "lvgl.h"

extern const lv_img_dsc_t emo_bg;

#define EMO_CX                   400
#define EMO_CY                   250
#define EMO_START                134
#define EMO_SWEEP                272
#define EMO_R_IN                 148
#define EMO_R_OUT                190
#define EMO_SEGS                 16
#define EMO_GAP                  2
#define EMO_BAR_W                150
#define EMO_BAR_H                34
#define EMO_TAB_Y                432
#define EMO_BAR0_X               18
#define EMO_BAR0_Y               44
#define EMO_BAR1_X               18
#define EMO_BAR1_Y               166
#define EMO_BAR2_X               632
#define EMO_BAR2_Y               44
#define EMO_BAR3_X               632
#define EMO_BAR3_Y               166
extern const lv_img_dsc_t lonk_bg;
extern const lv_img_dsc_t lonk_lit;

#define LONK_X0                  6
#define LONK_X1                  800
#define LONK_BIG_Y               150
#define LONK_SPEED_X1            330
#define LONK_RPM_X1              610
#define LONK_T0_X0               120
#define LONK_T0_Y0               288
#define LONK_T0_X1               392
#define LONK_T0_Y1               342
#define LONK_T1_X0               408
#define LONK_T1_Y0               288
#define LONK_T1_X1               786
#define LONK_T1_Y1               342
#define LONK_T2_X0               14
#define LONK_T2_Y0               372
#define LONK_T2_X1               258
#define LONK_T2_Y1               426
#define LONK_T3_X0               274
#define LONK_T3_Y0               372
#define LONK_T3_X1               518
#define LONK_T3_Y1               426
#define LONK_T4_X0               534
#define LONK_T4_Y0               372
#define LONK_T4_X1               786
#define LONK_T4_Y1               426
#define LONK_BOX_X0              640
#define LONK_BOX_Y0              136
#define LONK_BOX_X1              786
#define LONK_BOX_Y1              264
extern const lv_img_dsc_t hill_bg;
extern const lv_img_dsc_t hill_needle;
extern const lv_img_dsc_t hill_hub;

#define HILL_CX                  400
#define HILL_CY                  244
#define HILL_R                   176
#define HILL_START               90
#define HILL_SWEEP               290
#define HILL_TILE_W              208
#define HILL_TILE_H              146
#define HILL_SEGS                12
#define HILL_NEEDLE_PIVOT_X      29
#define HILL_NEEDLE_PIVOT_Y      9
#define HILL_T0_X                8
#define HILL_T0_Y                12
#define HILL_T1_X                8
#define HILL_T1_Y                167
#define HILL_T2_X                8
#define HILL_T2_Y                322
#define HILL_T3_X                584
#define HILL_T3_Y                12
#define HILL_T4_X                584
#define HILL_T4_Y                167
#define HILL_T5_X                584
#define HILL_T5_Y                322
static const char *const HILL_UNIT[6] = { "BAR", "AFR", "", "\xC2\xB0" "C", "\xC2\xB0" "C", "KPA" };
