/* Generated by tools/gen_faces.py, do not edit. */
#pragma once
#include "lvgl.h"

#define FACE_SIZE     466
#define FACE_START    135     /* degrees, 0 = 3 o'clock, clockwise */
#define FACE_SWEEP    270
#define FACE_ARC_R    212     /* centre line of the value arc */
#define FACE_ARC_W    14
#define FACE_GROOVE_W 21     /* the baked groove, for the red zone */
#define FACE_COUNT    6
#define FACE_TITLE_Y  61     /* live page title, centre above the centre */

/* RETRO: the red band, the ticks' outer end, the readout window */
#define RETRO_ZONE_R  210
#define RETRO_ZONE_W  7
#define RETRO_TICK_R  203
#define RETRO_WIN_TOP 77     /* from the centre */
#define RETRO_WIN_BOT 116
#define RETRO_WIN_W   116
#define RETRO_TITLE_Y 44     /* live title, above the centre */
#define RETRO_UNIT_Y  149     /* live unit, below the centre */

/* MULTI: the small gauges (from the centre), RETRO's readout window */
#define MULTI_MINI_DX 128
#define MULTI_MINI_Y  90
#define MULTI_MINI_R  50
#define RMULTI_WIN_TOP -103    /* from the centre, negative: above */
#define RMULTI_WIN_BOT -61
#define RMULTI_WIN_W  116

/* RETRO DPF: soot readout and the three small windows (from the centre) */
#define RDPF_MAX      40
#define RDPF_WIN_TOP  -103
#define RDPF_WIN_BOT  -61
#define RDPF_WIN_W    116
#define RDPF_SM_TOP   63
#define RDPF_SM_BOT   98
#define RDPF_SM_W     79
#define RDPF_SM_DX    98

/* FUTURO: the lit segments */
#define FUTURO_SEG_R  218
#define FUTURO_SEG_L  33

/* one row per page, in page order */
typedef struct {
    const char *unit;
    float lo, hi, warn;
} face_page_t;

static const face_page_t FACE_PAGE[FACE_COUNT] = {
    { "\xC2\xB0" "C", 40.0f, 140.0f, 105.0f },   /* WATER */
    { "\xC2\xB0" "C", 40.0f, 160.0f, 130.0f },   /* OIL */
    { "bar", 0.0f, 2.5f, 2.2f },   /* BOOST */
    { "\xC2\xB0" "C", 0.0f, 100.0f, 60.0f },   /* INTAKE */
    { "\xC2\xB0" "C", 0.0f, 1000.0f, 750.0f },   /* EXHAUST */
    { "rpm", 0.0f, 5000.0f, 4500.0f },   /* RPM */
};

extern const lv_img_dsc_t *const face_img[FACE_COUNT];
extern const lv_img_dsc_t *const face_retro_img[FACE_COUNT];
extern const lv_img_dsc_t *const page_icon[FACE_COUNT];   /* A8 */
extern const lv_img_dsc_t face_futuro_bg;
extern const lv_img_dsc_t face_retro_multi;
extern const lv_img_dsc_t face_retro_plain;
extern const lv_img_dsc_t face_retro_dpf;

/* A8 icons, recolour with img_recolor */
extern const lv_img_dsc_t icon_dpf_120;
extern const lv_img_dsc_t icon_dpf_40;
