/* Generated by tools/gen_faces.py, do not edit. */
#pragma once
#include "lvgl.h"

#define FACE_SIZE     480
#define FACE_START    135     /* degrees, 0 = 3 o'clock, clockwise */
#define FACE_SWEEP    270
#define FACE_ARC_R    219     /* centre line of the value arc */
#define FACE_ARC_W    15
#define FACE_COUNT    6

/* one row per page, in page order */
typedef struct {
    const char *unit;
    float lo, hi, warn;
} face_page_t;

static const face_page_t FACE_PAGE[FACE_COUNT] = {
    { "\xC2\xB0" "C", 40.0f, 140.0f, 105.0f },   /* WATER */
    { "\xC2\xB0" "C", 40.0f, 160.0f, 130.0f },   /* OIL */
    { "bar", 0.0f, 2.5f, 2.2f },   /* BOOST */
    { "\xC2\xB0" "C", 0.0f, 100.0f, 60.0f },   /* INTAKE */
    { "\xC2\xB0" "C", 0.0f, 1000.0f, 750.0f },   /* EXHAUST */
    { "rpm", 0.0f, 5000.0f, 4500.0f },   /* RPM */
};

extern const lv_img_dsc_t *const face_img[FACE_COUNT];

/* A8 icons, recolour with img_recolor */
extern const lv_img_dsc_t icon_dpf_120;
extern const lv_img_dsc_t icon_dpf_40;
