#!/usr/bin/env python3
"""Boot screen logo for the round gauge: assets/splash.png -> main/splash.c
(the same badge and keying as the 7" dash's tools/gen_splash.py)

The owner's round NOT STOCK. / NOT STABLE. badge, shown on black at power-up,
filling the round panel.

The source has a white background. It is keyed out on the blue channel: the
badge is only yellow and black, both with blue near zero, while the white
background has blue at 255. So blue / 255 is how much of a pixel is
background, and scaling the pixel by (1 - that) turns the background black
and keeps the antialiased rim of the disc smooth instead of leaving a white
fringe. The result is cropped to the disc and scaled to SIZE.

To change the logo, replace assets/splash.png (square-ish, any size, on white
or on black) and run this again. Other boot logos (the settings' LOGO row)
are drawn here, see LOGOS; one for another car goes on that list and on
RND_LOGO_* in ui_round.h.

Run from the project root:  python tools/gen_splash.py
"""
import os

import numpy as np
from PIL import Image, ImageChops, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
SOURCE = os.path.join(ROOT, "assets", "splash.png")

SIZE = 456                   # rendered size on the 480x480 round panel


def load():
    src = Image.open(SOURCE)
    if src.mode in ("RGBA", "LA", "P"):
        # flatten any transparency onto white, the keying below expects it
        bg = Image.new("RGBA", src.size, (255, 255, 255, 255))
        src = Image.alpha_composite(bg, src.convert("RGBA"))
    a = np.asarray(src.convert("RGB"), dtype=np.float32)

    bgness = a[..., 2] / 255.0
    out = a * (1.0 - bgness[..., None])

    # crop to the disc, square, with a hair of margin
    ys, xs = np.nonzero(bgness < 0.5)
    cx, cy = (xs.min() + xs.max()) / 2, (ys.min() + ys.max()) / 2
    half = max(xs.max() - xs.min(), ys.max() - ys.min()) / 2 * 1.02
    img = Image.fromarray(out.clip(0, 255).astype(np.uint8), "RGB")
    img = img.crop((int(cx - half), int(cy - half),
                    int(cx + half), int(cy + half)))
    return img.resize((SIZE, SIZE), Image.LANCZOS)


def vw():
    """VW roundel, drawn: dark blue disc, white ring, V over W (the flat
    2019 style). For the owner's own T5; it is VW's trademark."""
    ss = 4
    n = SIZE * ss
    c = n / 2
    R = n / 2 * 0.985
    img = Image.new("RGB", (n, n), (0, 0, 0))
    d = ImageDraw.Draw(img)
    blue, white = (0, 30, 80), (255, 255, 255)
    d.ellipse([c - R, c - R, c + R, c + R], fill=blue)
    ring_w = 0.055 * R
    r_in = 0.86 * R
    d.ellipse([c - R + ring_w, c - R + ring_w, c + R - ring_w, c + R - ring_w],
              fill=white)
    d.ellipse([c - r_in, c - r_in, c + r_in, c + r_in], fill=blue)

    # the letters, clipped to the inside of the ring
    letters = Image.new("L", (n, n), 0)
    ld = ImageDraw.Draw(letters)
    w = int(0.085 * R)

    def P(x, y):
        return (c + x * R, c + y * R)

    def stroke(pts):
        ld.line([P(*q) for q in pts], fill=255, width=w, joint="curve")

    stroke([(-0.42, -0.95), (0.0, 0.10), (0.42, -0.95)])          # V
    stroke([(-0.95, -0.36), (-0.44, 0.80), (0.0, -0.10 + 0.34),
            (0.44, 0.80), (0.95, -0.36)])                          # W
    inside = Image.new("L", (n, n), 0)
    ImageDraw.Draw(inside).ellipse([c - r_in, c - r_in, c + r_in, c + r_in],
                                   fill=255)
    letters = ImageChops.multiply(letters, inside)
    img.paste(Image.new("RGB", (n, n), white), (0, 0), letters)
    return img.resize((SIZE, SIZE), Image.LANCZOS)


# boot logos, in the order of RND_LOGO_* in ui_round.h
LOGOS = [("notstock", load), ("vw", vw)]


def c_image(name, img):
    w, h = img.size
    px = np.asarray(img, dtype=np.uint16)
    v = ((px[..., 0] & 0xF8) << 8) | ((px[..., 1] & 0xFC) << 3) | (px[..., 2] >> 3)
    out = [f"static const uint16_t {name}_map[{w*h}] = {{"]
    for row in v:
        out.append("    " + " ".join(f"0x{p:04x}," for p in row))
    out += ["};",
            f"const lv_img_dsc_t {name} = {{",
            "    .header = { .cf = LV_IMG_CF_TRUE_COLOR, .always_zero = 0,"
            f" .reserved = 0, .w = {w}, .h = {h} }},",
            f"    .data_size = {w*h*2},",
            f"    .data = (const uint8_t *){name}_map,",
            "};", ""]
    return out


def main():
    # uint16_t, not bytes: the pixels are read as 16-bit words, and a byte
    # array carries no alignment guarantee
    out = ["/* Generated by tools/gen_splash.py. Do not edit by hand.",
           " * Boot logos, RGB565, native byte order. */",
           '#include "lvgl.h"', ""]
    names = []
    for key, make in LOGOS:
        img = make()
        name = "boot_logo_" + key
        names.append(name)
        out += c_image(name, img)
        img.save(os.path.join(ROOT, "preview", "logo-%s.png" % key))
    out.append("const lv_img_dsc_t *const boot_logo[%d] = {" % len(LOGOS))
    out.append("    " + ", ".join("&" + n for n in names) + ",")
    out.append("};")
    open(os.path.join(ROOT, "main", "splash.c"), "w").write("\n".join(out) + "\n")
    print("wrote main/splash.c (%d logos, %d kB), preview/logo-*.png"
          % (len(LOGOS), len(LOGOS) * SIZE * SIZE * 2 // 1024))


if __name__ == "__main__":
    main()
