/* Generated by tools/gen_faces.py, do not edit. */
#pragma once
#include "lvgl.h"

#define FACE_SIZE     480
#define FACE_START    135     /* degrees, 0 = 3 o'clock, clockwise */
#define FACE_SWEEP    270
#define FACE_ARC_R    219     /* centre line of the value arc */
#define FACE_ARC_W    15
#define FACE_GROOVE_W 22     /* the baked groove, for the red zone */
#define FACE_COUNT    6
#define FACE_TITLE_Y  62     /* live page title, centre above the centre */

/* RETRO: the red band, the ticks' outer end, the readout window */
#define RETRO_ZONE_R  216
#define RETRO_ZONE_W  7
#define RETRO_TICK_R  209
#define RETRO_WIN_TOP 79     /* from the centre */
#define RETRO_WIN_BOT 120
#define RETRO_WIN_W   120
#define RETRO_TITLE_Y 46     /* live title, above the centre */
#define RETRO_UNIT_Y  154     /* live unit, below the centre */

/* MULTI: the small gauges (from the centre), RETRO's readout window */
#define MULTI_MINI_DX 132
#define MULTI_MINI_Y  92
#define MULTI_MINI_R  52
#define RMULTI_WIN_TOP -106    /* from the centre, negative: above */
#define RMULTI_WIN_BOT -62
#define RMULTI_WIN_W  120

/* RETRO DPF: soot readout and the three small windows (from the centre) */
#define RDPF_MAX      40
#define RDPF_WIN_TOP  -106
#define RDPF_WIN_BOT  -62
#define RDPF_WIN_W    120
#define RDPF_SM_TOP   65
#define RDPF_SM_BOT   101
#define RDPF_SM_W     82
#define RDPF_SM_DX    101

/* FUTURO: the lit segments */
#define FUTURO_SEG_R  224
#define FUTURO_SEG_L  34

/* one row per page, in page order */
typedef struct {
    const char *unit;
    float lo, hi, warn;
} face_page_t;

static const face_page_t FACE_PAGE[FACE_COUNT] = {
    { "\xC2\xB0" "C", 40.0f, 140.0f, 105.0f },   /* WATER */
    { "\xC2\xB0" "C", 40.0f, 160.0f, 130.0f },   /* OIL */
    { "bar", 0.0f, 2.5f, 2.2f },   /* BOOST */
    { "\xC2\xB0" "C", 0.0f, 100.0f, 60.0f },   /* INTAKE */
    { "\xC2\xB0" "C", 0.0f, 1000.0f, 750.0f },   /* EXHAUST */
    { "rpm", 0.0f, 5000.0f, 4500.0f },   /* RPM */
};

extern const lv_img_dsc_t *const face_img[FACE_COUNT];
extern const lv_img_dsc_t *const face_retro_img[FACE_COUNT];
extern const lv_img_dsc_t *const page_icon[FACE_COUNT];   /* A8 */
extern const lv_img_dsc_t face_futuro_bg;
extern const lv_img_dsc_t face_retro_multi;
extern const lv_img_dsc_t face_retro_plain;
extern const lv_img_dsc_t face_retro_dpf;

/* A8 icons, recolour with img_recolor */
extern const lv_img_dsc_t icon_dpf_120;
extern const lv_img_dsc_t icon_dpf_40;
