#!/usr/bin/env python3
"""Pre-render the static artwork of the alternative looks (EMO, LONK, HILL).

Each look is one full-screen 800x480 background with every static part baked
in: scales, numbers, frames, labels, textures. LVGL then only draws what
moves (segments, bar fills, needles, numbers), same idea as gen_dials.py.

These are our own drawings in the spirit of well-known aftermarket dashes;
no logos or trademarks are reproduced.

Outputs
    main/theme_art.h        externs and every geometry number the C side needs
    main/theme_art_emo.c    EMO background
    main/theme_art_lonk.c   LONK background and the lit rev band
    main/theme_art_hill.c   HILL background, needle and hub
    build_art/theme_*.png   the same images, for a quick look

Run from the project root:  python tools/gen_themes.py
"""
import math
import os
import sys

import numpy as np
from PIL import Image, ImageDraw, ImageFilter, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
FONTS = os.path.join(ROOT, "assets", "fonts")
sys.path.insert(0, HERE)
import gen_dials  # noqa: E402  (needle and hub builders)

W, H = 800, 480
SS = 3                                   # supersample for the backgrounds

HEADER = []                              # lines for theme_art.h


def define(k, v):
    HEADER.append(f"#define {k:<24} {v}")


def f_(name, px):
    return ImageFont.truetype(os.path.join(FONTS, name), int(round(px * SS)))


def u(v):
    return v * SS


def canvas(bg=(0, 0, 0)):
    img = Image.new("RGB", (W * SS, H * SS), bg)
    return img, ImageDraw.Draw(img)


def pt(cx, cy, r, a):
    a = math.radians(a)
    return cx + r * math.cos(a), cy + r * math.sin(a)


def sector(d, cx, cy, r0, r1, a0, a1, col, steps=None):
    steps = steps or max(6, int(abs(a1 - a0) * 3))
    p = [pt(cx, cy, r1, a0 + (a1 - a0) * i / steps) for i in range(steps + 1)]
    p += [pt(cx, cy, r0, a0 + (a1 - a0) * i / steps)
          for i in range(steps, -1, -1)]
    d.polygon(p, fill=col)


def radial(d, cx, cy, r0, r1, a, w, col):
    x0, y0 = pt(cx, cy, r0, a)
    x1, y1 = pt(cx, cy, r1, a)
    d.line([(x0, y0), (x1, y1)], fill=col, width=int(round(w)))


def text_c(d, x, y, t, f, col):
    bb = d.textbbox((0, 0), t, font=f)
    d.text((x - (bb[0] + bb[2]) / 2, y - (bb[1] + bb[3]) / 2), t, font=f,
           fill=col)


def finish(img):
    return img.resize((W, H), Image.LANCZOS)


def emit565(name, img, path_list):
    """RGB565 as uint16_t words, same format as gen_splash.py."""
    a = np.asarray(img.convert("RGB"), dtype=np.uint16)
    v = ((a[..., 0] & 0xF8) << 8) | ((a[..., 1] & 0xFC) << 3) | (a[..., 2] >> 3)
    h, w = v.shape
    out = [f"static const uint16_t {name}_map[{w*h}] = {{"]
    for row in v:
        out.append("    " + " ".join(f"0x{p:04x}," for p in row))
    out += ["};",
            f"const lv_img_dsc_t {name} = {{",
            "    .header = { .cf = LV_IMG_CF_TRUE_COLOR, .always_zero = 0,"
            f" .reserved = 0, .w = {w}, .h = {h} }},",
            f"    .data_size = {w*h*2},",
            f"    .data = (const uint8_t *){name}_map,",
            "};", ""]
    path_list.extend(out)
    HEADER.append(f"extern const lv_img_dsc_t {name};")


def write(fname, body):
    head = ["/* Generated by tools/gen_themes.py - do not edit by hand. */",
            '#include "ui.h"', ""]
    open(os.path.join(ROOT, "main", fname), "w").write("\n".join(head + body))


def save_png(name, img):
    d = os.path.join(ROOT, "build_art")
    os.makedirs(d, exist_ok=True)
    img.save(os.path.join(d, name + ".png"))


# ======================================================================= EMO
EMO_CX, EMO_CY = 400, 250
# whole degrees per segment (272 / 16 = 17), so the LVGL arcs that light a
# segment land exactly on the baked grey one
EMO_START, EMO_SWEEP = 134, 272          # 0 rpm at 134 deg, 8000 at 46 deg
EMO_R_IN, EMO_R_OUT = 148, 190           # segment band
EMO_SEGS = 16                            # 500 rpm each
EMO_GAP = 2                              # degrees between segments
EMO_BAR_W, EMO_BAR_H = 150, 34
EMO_BARS = [                             # x, y of the bar box, label, lo, hi, step
    (18, 44, "WATER TEMP", 40, 120, 40),
    (18, 166, "INTAKE TEMP", 0, 80, 40),
    (632, 44, "BOOST", -1, 2, 1),
    (632, 166, "AFR", 10, 18, 4),
]
EMO_TAB_Y = 432                          # bottom tabs, top edge
YEL = (255, 204, 0)


def perforated(img, base, hole, pitch=6, r=1.5):
    """Perforated metal: a grid of dark holes, offset every other row."""
    d = ImageDraw.Draw(img)
    p = u(pitch)
    rr = u(r)
    y = 0
    row = 0
    while y < img.size[1] + p:
        x = (p / 2) if row % 2 else 0
        while x < img.size[0] + p:
            d.ellipse([x - rr, y - rr, x + rr, y + rr], fill=hole)
            x += p
        y += p * 0.866
        row += 1


def vignette(img, strength):
    w, h = img.size
    yy, xx = np.mgrid[0:h, 0:w].astype(np.float32)
    dx = (xx - w / 2) / (w / 2)
    dy = (yy - h / 2) / (h / 2)
    k = 1 - strength * np.clip(np.sqrt(dx * dx * 0.6 + dy * dy), 0, 1.4) ** 2
    a = np.asarray(img, dtype=np.float32) * k[..., None]
    return Image.fromarray(np.clip(a, 0, 255).astype(np.uint8), "RGB")


def build_emo():
    img, d = canvas((0x27, 0x29, 0x2C))
    perforated(img, None, (0x12, 0x13, 0x14))
    img = vignette(img, 0.45)
    d = ImageDraw.Draw(img)
    cx, cy = u(EMO_CX), u(EMO_CY)

    # darker centre disc and the thin inner ring
    ov = Image.new("RGBA", img.size, (0, 0, 0, 0))
    ImageDraw.Draw(ov).ellipse([cx - u(EMO_R_IN - 6), cy - u(EMO_R_IN - 6),
                                cx + u(EMO_R_IN - 6), cy + u(EMO_R_IN - 6)],
                               fill=(0, 0, 0, 110))
    img = Image.alpha_composite(img.convert("RGBA"), ov).convert("RGB")
    d = ImageDraw.Draw(img)
    sector(d, cx, cy, u(EMO_R_IN - 9), u(EMO_R_IN - 6), EMO_START,
           EMO_START + EMO_SWEEP, (0x5A, 0x5D, 0x61))

    # unlit segments, grey with a radial shade
    seg = EMO_SWEEP / EMO_SEGS
    for i in range(EMO_SEGS):
        a0 = EMO_START + i * seg + EMO_GAP / 2
        a1 = EMO_START + (i + 1) * seg - EMO_GAP / 2
        for k in range(8):
            r0 = EMO_R_IN + (EMO_R_OUT - EMO_R_IN) * k / 8
            r1 = EMO_R_IN + (EMO_R_OUT - EMO_R_IN) * (k + 1) / 8
            g = int(0x50 + 0x38 * k / 7)
            sector(d, cx, cy, u(r0), u(r1) + 1, a0, a1, (g, g, g + 2))

    # scale line, ticks, numbers
    r_line = EMO_R_OUT + 8
    sector(d, cx, cy, u(r_line - 1.6), u(r_line + 1.6), EMO_START,
           EMO_START + EMO_SWEEP, (0xE8, 0xE8, 0xE8))
    for i in range(EMO_SEGS + 1):
        a = EMO_START + i * seg
        major = i % 2 == 0
        radial(d, cx, cy, u(r_line), u(r_line + (13 if major else 8)), a,
               u(3.2 if major else 2.2), (0xE8, 0xE8, 0xE8))
    f = f_("Exo2-SemiBold.ttf", 30)
    for k in range(9):
        a = EMO_START + k * 2 * seg
        x, y = pt(cx, cy, u(r_line + 28), a)
        text_c(d, x, y, str(k), f, (0xF0, 0xF0, 0xF0))

    # corner accents: thin lines from the side with a ring on the end
    for side in (0, 1):
        x0 = 0 if side == 0 else W
        x1 = 206 if side == 0 else W - 206
        d.line([(u(x0), u(262)), (u(x1), u(392))], fill=(0x8C, 0x90, 0x94),
               width=u(2))
        d.ellipse([u(x1 - 6), u(392 - 6), u(x1 + 6), u(392 + 6)],
                  outline=(0xC8, 0xCC, 0xD0), width=u(2))

    # bar gauges: scale above, box, bracket with label below
    fs = f_("Exo2-SemiBold.ttf", 20)
    fl = f_("Exo2-SemiBold.ttf", 15)
    wht = (0xF0, 0xF0, 0xF0)
    for x, y, label, lo, hi, step in EMO_BARS:
        # scale: line with end and middle ticks, numbers above
        ly = y - 12
        d.line([(u(x), u(ly)), (u(x + EMO_BAR_W), u(ly))], fill=wht, width=u(2))
        n = int(round((hi - lo) / step))
        for i in range(n + 1):
            tx = x + EMO_BAR_W * i / n
            d.line([(u(tx), u(ly)), (u(tx), u(ly - 8))], fill=wht, width=u(2))
            v = lo + i * step
            text_c(d, u(tx), u(ly - 22), f"{v:g}", fs, wht)
        # box: dark frame, grey inside (the fill is live)
        d.rectangle([u(x - 2), u(y - 2), u(x + EMO_BAR_W + 2), u(y + EMO_BAR_H + 2)],
                    fill=(0x10, 0x10, 0x11))
        for k in range(EMO_BAR_H):
            g = int(0x9A - 0x28 * k / EMO_BAR_H)
            d.line([(u(x), u(y + k)), (u(x + EMO_BAR_W), u(y + k))],
                   fill=(g, g, g + 2), width=u(1) + 1)
        # bracket
        by = y + EMO_BAR_H + 16
        bb = d.textbbox((0, 0), label, font=fl)
        tw = (bb[2] - bb[0]) / SS
        mid = x + EMO_BAR_W / 2
        for xa, xb in ((x - 12, mid - tw / 2 - 6), (mid + tw / 2 + 6,
                                                     x + EMO_BAR_W + 12)):
            d.line([(u(xa), u(by)), (u(xb), u(by))], fill=wht, width=u(2))
        d.line([(u(x - 12), u(by)), (u(x - 12), u(by - 10))], fill=wht, width=u(2))
        d.line([(u(x + EMO_BAR_W + 12), u(by)), (u(x + EMO_BAR_W + 12), u(by - 10))],
               fill=wht, width=u(2))
        text_c(d, u(mid), u(by), label, fl, wht)

    # bottom tabs, yellow, cut on the inner end
    ty = EMO_TAB_Y
    d.polygon([(0, u(ty)), (u(200), u(ty)), (u(234), u(474)), (0, u(474))],
              fill=YEL)
    d.polygon([(u(W), u(ty)), (u(W - 200), u(ty)), (u(W - 234), u(474)),
               (u(W), u(474))], fill=YEL)
    fl2 = f_("Exo2-SemiBold.ttf", 14)
    blk = (0x10, 0x10, 0x10)
    my = (ty + 474) / 2
    text_c(d, u(44), u(my), "LAMBDA", fl2, blk)
    text_c(d, u(W - 34), u(my), "kPa", fl2, blk)
    text_c(d, u(W - 186), u(my), "MAP", fl2, blk)

    img = finish(img)
    save_png("theme_emo", img)
    body = []
    emit565("emo_bg", img, body)
    write("theme_art_emo.c", body)

    HEADER.append("")
    define("EMO_CX", EMO_CX)
    define("EMO_CY", EMO_CY)
    define("EMO_START", EMO_START)
    define("EMO_SWEEP", EMO_SWEEP)
    define("EMO_R_IN", EMO_R_IN)
    define("EMO_R_OUT", EMO_R_OUT)
    define("EMO_SEGS", EMO_SEGS)
    define("EMO_GAP", EMO_GAP)
    define("EMO_BAR_W", EMO_BAR_W)
    define("EMO_BAR_H", EMO_BAR_H)
    define("EMO_TAB_Y", EMO_TAB_Y)
    for i, (x, y, *_r) in enumerate(EMO_BARS):
        define(f"EMO_BAR{i}_X", x)
        define(f"EMO_BAR{i}_Y", y)


# ====================================================================== LONK
LONK_BAND_T = 58                          # band thickness
LONK_BAND_Y = 58                          # centre line of the straight part
LONK_CURVE_CX, LONK_CURVE_R = 236, 190    # quarter circle at the left
NAVY = (0x1C, 0x33, 0x54)
LONK_BAND_H = 300                         # height of the lit band image


def lonk_band_mask(scale):
    """Band shape as a mask: quarter circle rising from the left edge into a
    straight strip along the top."""
    m = Image.new("L", (W * scale, LONK_BAND_H * scale), 0)
    d = ImageDraw.Draw(m)
    s = lambda v: v * scale
    ccy = LONK_BAND_Y + LONK_CURVE_R
    ro, ri = LONK_CURVE_R + LONK_BAND_T / 2, LONK_CURVE_R - LONK_BAND_T / 2
    sector(d, s(LONK_CURVE_CX), s(ccy), s(ri), s(ro), 180, 270, 255)
    d.rectangle([s(LONK_CURVE_CX), s(LONK_BAND_Y - LONK_BAND_T / 2),
                 s(W), s(LONK_BAND_Y + LONK_BAND_T / 2)], fill=255)
    return m


def lonk_x(rpm):
    """x position where the lit band ends at a given rpm; the C side uses
    the same linear map (LONK_X0, LONK_X1)."""
    return LONK_X0 + (LONK_X1 - LONK_X0) * rpm / 8000


LONK_X0, LONK_X1 = 6, 800


def build_lonk():
    # steel blue gradient with faint brushed lines
    top, bot = np.array([0xEC, 0xF1, 0xF5]), np.array([0x93, 0xA9, 0xBC])
    t = np.linspace(0, 1, H * SS)[:, None, None]
    a = top + (bot - top) * t ** 0.9
    a = np.repeat(a, W * SS, axis=1)
    rng = np.random.default_rng(3)
    brush = rng.normal(0, 1.6, (H * SS, 1, 1))
    a = np.clip(a + brush, 0, 255).astype(np.uint8)
    img = Image.fromarray(a, "RGB")
    d = ImageDraw.Draw(img)

    # unlit band: slate with vertical pin stripes
    mask = lonk_band_mask(SS)
    unlit = Image.new("RGB", mask.size, (0x7E, 0x91, 0xA3))
    ud = ImageDraw.Draw(unlit)
    for x in range(0, mask.size[0], u(5)):
        ud.line([(x, 0), (x, mask.size[1])], fill=(0x72, 0x84, 0x96), width=u(1))
    img.paste(unlit, (0, 0), mask)

    # navy rule under the band, following its lower edge
    ccy = LONK_BAND_Y + LONK_CURVE_R
    ri = LONK_CURVE_R - LONK_BAND_T / 2
    sector(d, u(LONK_CURVE_CX), u(ccy), u(ri - 7), u(ri - 4), 180, 270, NAVY)
    d.rectangle([u(LONK_CURVE_CX), u(LONK_BAND_Y + LONK_BAND_T / 2 + 4),
                 u(W), u(LONK_BAND_Y + LONK_BAND_T / 2 + 7)], fill=NAVY)

    # ticks and numbers under the band, at the band's lit end for each 1000
    fnum = f_("Orbitron-Black.ttf", 22)
    for k in range(1, 8):
        x = lonk_x(k * 1000)
        if x >= LONK_CURVE_CX:
            y = LONK_BAND_Y + LONK_BAND_T / 2 + 8
            d.polygon([(u(x - 6), u(y + 12)), (u(x + 6), u(y + 12)),
                       (u(x), u(y + 2))], fill=(0x55, 0x67, 0x7A))
            text_c(d, u(x), u(y + 30), str(k), fnum, NAVY)
        else:
            # on the curve: find the inner edge point with this x
            dx = LONK_CURVE_CX - x
            dy = math.sqrt(max(ri * ri - dx * dx, 0))
            y = ccy - dy
            ang = math.atan2(-dy, -dx)
            nx, ny = -math.cos(ang), -math.sin(ang)     # towards the centre
            text_c(d, u(x + nx * 30), u(y + ny * 30), str(k), fnum, NAVY)

    # tiles and the boost box
    fl = f_("Exo2-SemiBold.ttf", 16)
    grey = (0x5A, 0x6E, 0x84)

    def tile(x0, y0, x1, y1, label):
        d.rounded_rectangle([u(x0), u(y0), u(x1), u(y1)], radius=u(8),
                            fill=(0xE4, 0xEB, 0xF1), outline=(0xB9, 0xC7, 0xD4),
                            width=u(2))
        if label:
            bb = d.textbbox((0, 0), label, font=fl)
            d.text((u(x1 - 6) - bb[2], u(y1 + 3)), label, font=fl, fill=grey)

    for x0, y0, x1, y1, lab in LONK_TILES:
        tile(x0, y0, x1, y1, lab)
    bx0, by0, bx1, by1 = LONK_BOX
    d.rounded_rectangle([u(bx0 - 4), u(by0 - 4), u(bx1 + 4), u(by1 + 4)],
                        radius=u(12), fill=(0xA8, 0xB4, 0xBF))
    d.rounded_rectangle([u(bx0), u(by0), u(bx1), u(by1)], radius=u(9),
                        fill=(0xF2, 0xF5, 0xF8), outline=(0x6C, 0x7B, 0x8A),
                        width=u(2))
    text_c(d, u((bx0 + bx1) / 2), u(by0 + 22), "BOOST", fl, grey)
    text_c(d, u((bx0 + bx1) / 2), u(by1 - 20), "bar", fl, grey)

    # unit labels under the two big numbers
    fu = f_("Exo2-SemiBold.ttf", 17)
    blu = (0x2F, 0x6D, 0xB5)
    for x, t_ in ((LONK_SPEED_X1, "km/h"), (LONK_RPM_X1, "rpm")):
        bb = d.textbbox((0, 0), t_, font=fu)
        d.text((u(x) - bb[2], u(LONK_BIG_Y + 70)), t_, font=fu, fill=blu)

    # info line
    d.rectangle([0, u(452), u(W), u(H)], fill=(0x1E, 0x3A, 0x5C))
    d.rectangle([0, u(450), u(W), u(452)], fill=(0xC9, 0xD4, 0xDE))

    bg = finish(img)

    # lit band: the background with the band painted white, red past 7000
    lit = img.copy()
    white = Image.new("RGB", mask.size, (0xFF, 0xFF, 0xFF))
    wd = ImageDraw.Draw(white)
    for x in range(0, mask.size[0], u(5)):
        wd.line([(x, 0), (x, mask.size[1])], fill=(0xDD, 0xE4, 0xEA), width=u(1))
    red_x = int(u(lonk_x(7000)))
    wd.rectangle([red_x, 0, mask.size[0], mask.size[1]], fill=(0xE0, 0x2A, 0x2A))
    for x in range(red_x, mask.size[0], u(5)):
        wd.line([(x, 0), (x, mask.size[1])], fill=(0xC4, 0x20, 0x20), width=u(1))
    lit.paste(white, (0, 0), mask)
    lit = finish(lit).crop((0, 0, W, LONK_BAND_H))

    save_png("theme_lonk", bg)
    save_png("theme_lonk_lit", lit)
    body = []
    emit565("lonk_bg", bg, body)
    emit565("lonk_lit", lit, body)
    write("theme_art_lonk.c", body)

    HEADER.append("")
    define("LONK_X0", LONK_X0)
    define("LONK_X1", LONK_X1)
    define("LONK_BIG_Y", LONK_BIG_Y)
    define("LONK_SPEED_X1", LONK_SPEED_X1)
    define("LONK_RPM_X1", LONK_RPM_X1)
    for i, (x0, y0, x1, y1, _l) in enumerate(LONK_TILES):
        define(f"LONK_T{i}_X0", x0)
        define(f"LONK_T{i}_Y0", y0)
        define(f"LONK_T{i}_X1", x1)
        define(f"LONK_T{i}_Y1", y1)
    define("LONK_BOX_X0", LONK_BOX[0])
    define("LONK_BOX_Y0", LONK_BOX[1])
    define("LONK_BOX_X1", LONK_BOX[2])
    define("LONK_BOX_Y1", LONK_BOX[3])


LONK_BIG_Y = 150                          # top of the speed / rpm numbers
LONK_SPEED_X1 = 330                       # right edge of the speed number
LONK_RPM_X1 = 610
LONK_BOX = (640, 136, 786, 264)
LONK_TILES = [                            # x0, y0, x1, y1, label under it
    (120, 288, 392, 342, "AFR"),
    (408, 288, 786, 342, "MAP"),
    (14, 372, 258, 426, "INTAKE TEMP"),
    (274, 372, 518, 426, "WATER TEMP"),
    (534, 372, 786, 426, "LAMBDA"),
]


# ====================================================================== HILL
HILL_CX, HILL_CY = 400, 244
HILL_R = 176                              # face
HILL_START, HILL_SWEEP = 90, 290          # 0 at the bottom, clockwise
HILL_TILE_W, HILL_TILE_H = 208, 146
HILL_TILES = [                            # x, y, bar on the left?
    (8, 12, True), (8, 167, True), (8, 322, True),
    (584, 12, False), (584, 167, False), (584, 322, False),
]
HILL_LABELS = ["BOOST", "AIR FUEL RATIO", "LAMBDA",
               "COOLANT TEMP", "INTAKE TEMP", "MAP"]
HILL_UNITS = ["BAR", "AFR", "", "°C", "°C", "KPA"]
HILL_SEGS = 12                            # bargraph segments per tile
HILL_NEEDLE_LEN = 160
HILL_HUB = 56


def build_hill():
    img, d = canvas((0x1C, 0x1D, 0x1F))
    img = vignette(img, 0.35)
    d = ImageDraw.Draw(img)
    cx, cy = u(HILL_CX), u(HILL_CY)

    # bezel
    d.ellipse([cx - u(HILL_R + 12), cy - u(HILL_R + 12), cx + u(HILL_R + 12),
               cy + u(HILL_R + 12)], fill=(0x0C, 0x0C, 0x0D))
    d.ellipse([cx - u(HILL_R + 8), cy - u(HILL_R + 8), cx + u(HILL_R + 8),
               cy + u(HILL_R + 8)], fill=(0x3A, 0x3B, 0x3E))
    d.ellipse([cx - u(HILL_R + 3), cy - u(HILL_R + 3), cx + u(HILL_R + 3),
               cy + u(HILL_R + 3)], fill=(0x10, 0x10, 0x11))

    # face: yellow, red wedge past 7000
    def ang(rpm):
        return HILL_START + HILL_SWEEP * rpm / 8000

    d.ellipse([cx - u(HILL_R), cy - u(HILL_R), cx + u(HILL_R), cy + u(HILL_R)],
              fill=(0xFF, 0xD2, 0x1A))
    sector(d, cx, cy, 0, u(HILL_R), ang(7000), ang(8000) + 4,
           (0xE0, 0x2A, 0x2A))
    # dark centre
    d.ellipse([cx - u(64), cy - u(64), cx + u(64), cy + u(64)],
              fill=(0x16, 0x16, 0x17))

    blk = (0x12, 0x12, 0x12)
    for i in range(0, 33):
        rpm = i * 250
        a = ang(rpm)
        major = rpm % 1000 == 0
        half = rpm % 500 == 0
        col = (0xFF, 0xFF, 0xFF) if rpm >= 7000 else blk
        ln = 22 if major else (14 if half else 9)
        radial(d, cx, cy, u(HILL_R - 4), u(HILL_R - 4 - ln), a,
               u(5 if major else 2.4), col)
    fn = f_("BarlowCondensed-Bold.ttf", 44)
    for k in range(9):
        col = (0xFF, 0xFF, 0xFF) if k >= 7 else blk
        x, y = pt(cx, cy, u(HILL_R - 50), ang(k * 1000))
        text_c(d, x, y, str(k), fn, col)
    fx = f_("BarlowCondensed-SemiBold.ttf", 16)
    text_c(d, cx, cy - u(HILL_R - 88), "x1000 RPM", fx, blk)

    # tiles with an empty bargraph slot on the outer edge
    fl = f_("BarlowCondensed-SemiBold.ttf", 17)
    for (x, y, left), lab in zip(HILL_TILES, HILL_LABELS):
        d.rounded_rectangle([u(x), u(y), u(x + HILL_TILE_W), u(y + HILL_TILE_H)],
                            radius=u(6), fill=(0x26, 0x27, 0x29),
                            outline=(0x3A, 0x3B, 0x3E), width=u(2))
        bx = x + 10 if left else x + HILL_TILE_W - 34
        seg_h = (HILL_TILE_H - 24) / HILL_SEGS
        for s in range(HILL_SEGS):
            sy = y + 12 + s * seg_h
            d.rectangle([u(bx), u(sy + 1.5), u(bx + 24), u(sy + seg_h - 1.5)],
                        fill=(0x3A, 0x38, 0x2A))
        tx = x + 44 if left else x + 12
        d.text((u(tx), u(y + HILL_TILE_H - 30)), lab, font=fl,
               fill=(0xE8, 0xE8, 0xE8))

    img = finish(img)
    save_png("theme_hill", img)

    needle, piv = gen_dials.build_needle(HILL_NEEDLE_LEN, 12, 4, 26)
    hub = gen_dials.build_hub(HILL_HUB)
    body = []
    emit565("hill_bg", img, body)
    gen_dials.emit_rgba("hill_needle", needle, body)
    gen_dials.emit_rgba("hill_hub", hub, body)
    HEADER.append("extern const lv_img_dsc_t hill_needle;")
    HEADER.append("extern const lv_img_dsc_t hill_hub;")
    write("theme_art_hill.c", body)

    HEADER.append("")
    define("HILL_CX", HILL_CX)
    define("HILL_CY", HILL_CY)
    define("HILL_R", HILL_R)
    define("HILL_START", HILL_START)
    define("HILL_SWEEP", HILL_SWEEP)
    define("HILL_TILE_W", HILL_TILE_W)
    define("HILL_TILE_H", HILL_TILE_H)
    define("HILL_SEGS", HILL_SEGS)
    define("HILL_NEEDLE_PIVOT_X", piv[0])
    define("HILL_NEEDLE_PIVOT_Y", piv[1])
    for i, (x, y, left) in enumerate(HILL_TILES):
        define(f"HILL_T{i}_X", x)
        define(f"HILL_T{i}_Y", y)
    # the degree sign is split into its own string literal: "\xC2\xB0C"
    # would read as the hex escape \xB0C and swallow the C
    def c_str(t):
        return '"' + t.replace("\u00b0", '\\xC2\\xB0" "') + '"'
    HEADER.append("static const char *const HILL_UNIT[6] = { " +
                  ", ".join(c_str(t) for t in HILL_UNITS) + " };")


def main():
    build_emo()
    build_lonk()
    build_hill()
    h = ["/* Generated by tools/gen_themes.py - do not edit by hand. */",
         "#pragma once", '#include "lvgl.h"', ""] + HEADER + [""]
    open(os.path.join(ROOT, "main", "theme_art.h"), "w").write("\n".join(h))
    print("wrote main/theme_art*.{c,h}, build_art/theme_*.png")


if __name__ == "__main__":
    main()
