#!/usr/bin/env python3
"""Boot screen logo: assets/splash.png -> main/splash.c

The owner's round NOT STOCK. / NOT STABLE. badge, shown on black at power-up.

The source has a white background. It is keyed out on the blue channel: the
badge is only yellow and black, both with blue near zero, while the white
background has blue at 255. So blue / 255 is how much of a pixel is
background, and scaling the pixel by (1 - that) turns the background black
and keeps the antialiased rim of the disc smooth instead of leaving a white
fringe. The result is cropped to the disc and scaled to SIZE.

To change the logo, replace assets/splash.png (square-ish, any size, on white
or on black) and run this again.

Run from the project root:  python tools/gen_splash.py
"""
import os

import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
SOURCE = os.path.join(ROOT, "assets", "splash.png")

SIZE = 440                   # rendered size on the 800x480 panel, square


def load():
    src = Image.open(SOURCE)
    if src.mode in ("RGBA", "LA", "P"):
        # flatten any transparency onto white, the keying below expects it
        bg = Image.new("RGBA", src.size, (255, 255, 255, 255))
        src = Image.alpha_composite(bg, src.convert("RGBA"))
    a = np.asarray(src.convert("RGB"), dtype=np.float32)

    bgness = a[..., 2] / 255.0
    out = a * (1.0 - bgness[..., None])

    # crop to the disc, square, with a hair of margin
    ys, xs = np.nonzero(bgness < 0.5)
    cx, cy = (xs.min() + xs.max()) / 2, (ys.min() + ys.max()) / 2
    half = max(xs.max() - xs.min(), ys.max() - ys.min()) / 2 * 1.02
    img = Image.fromarray(out.clip(0, 255).astype(np.uint8), "RGB")
    img = img.crop((int(cx - half), int(cy - half),
                    int(cx + half), int(cy + half)))
    return img.resize((SIZE, SIZE), Image.LANCZOS)


def main():
    img = load()
    w, h = img.size
    px = np.asarray(img, dtype=np.uint16)
    v = ((px[..., 0] & 0xF8) << 8) | ((px[..., 1] & 0xFC) << 3) | (px[..., 2] >> 3)
    data = np.stack([v & 0xFF, v >> 8], axis=-1).reshape(h, w * 2)

    out = ["/* Generated by tools/gen_splash.py from assets/splash.png.",
           " * Do not edit by hand. */",
           '#include "ui.h"', "",
           f"static const uint8_t splash_logo_map[{w*h*2}] = {{"]
    for row in data:
        out.append("    " + " ".join(f"0x{b:02x}," for b in row))
    out += ["};",
            "const lv_img_dsc_t splash_logo = {",
            "    .header = { .cf = LV_IMG_CF_TRUE_COLOR, .always_zero = 0,"
            f" .reserved = 0, .w = {w}, .h = {h} }},",
            f"    .data_size = {w*h*2},",
            "    .data = splash_logo_map,",
            "};", ""]
    open(os.path.join(ROOT, "main", "splash.c"), "w").write("\n".join(out))
    os.makedirs(os.path.join(ROOT, "build_art"), exist_ok=True)
    img.save(os.path.join(ROOT, "build_art", "splash.png"))
    print(f"wrote main/splash.c ({w}x{h}, {w*h*2/1024:.0f} kB), "
          "build_art/splash.png")


if __name__ == "__main__":
    main()
